# Data cleaning of Aitbnb dataset

## Import data

In [222]:
import pandas as pd

In [223]:
df = pd.read_csv(r"D:\Data sets\Data cleaning Project\Pb5_Airbnb\Airbnb_Open_Data.csv", low_memory = False)

Due to having multiple data types at once neet to uplode at a same time given low memory = False
The low_memory option is a boolean parameter that controls whether 
Pandas should read the CSV file in chunks or load the entire file into memory at once. By default, low_memory is set to True, 
which means Pandas will attempt to read the file in chunks to conserve memory.

In [225]:
df.head()

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license
0,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,...,$193,10.0,9.0,10/19/2021,0.21,4.0,6.0,286.0,Clean up and treat the home the way you'd like...,NaN
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,...,$28,30.0,45.0,5/21/2022,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...,NaN
2,1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,...,$124,3.0,0.0,NaN,NaN,5.0,1.0,352.0,"I encourage you to use my kitchen, cooking and...",NaN
3,1002755,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,...,$74,30.0,270.0,7/5/2019,4.64,4.0,1.0,322.0,NaN,NaN
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,...,$41,10.0,9.0,11/19/2018,0.10,3.0,1.0,289.0,"Please no smoking in the house, porch or on th...",NaN

In [226]:
df.columns

Index(['id', 'NAME', 'host id', 'host_identity_verified', 'host name',
       'neighbourhood group', 'neighbourhood', 'lat', 'long', 'country',
       'country code', 'instant_bookable', 'cancellation_policy', 'room type',
       'Construction year', 'price', 'service fee', 'minimum nights',
       'number of reviews', 'last review', 'reviews per month',
       'review rate number', 'calculated host listings count',
       'availability 365', 'house_rules', 'license'],
      dtype='object')

## Checking Data informaation

In [228]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 102599 entries, 0 to 102598
Data columns (total 26 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   id                              102599 non-null  int64
 1   NAME                            102349 non-null  object
 2   host id                         102599 non-null  int64
 3   host_identity_verified          102310 non-null  object
 4   host name                       102193 non-null  object
 5   neighbourhood group             102570 non-null  object
 6   neighbourhood                   102583 non-null  object
 7   lat                             102591 non-null  float64
 8   long                            102591 non-null  float64
 9   country                         102067 non-null  object
 10  country code                    102468 non-null  object
 11  instant_bookable                102494 non-null  object
 12  cancellation_policy             102523 non-null  object
 13  room type                       102599 non-null  object
 14  Construction year               102385 non-null  float64
 15  price                           102352 non-null  object
 16  service fee                     102326 non-null  object
 17  minimum nights                  102190 non-null  float64
 18  number of reviews               102416 non-null  float64
 19  last review                     86706 non-null   object
 20  reviews per month               86720 non-null   float64
 21  review rate number              102273 non-null  float64
 22  calculated host listings count  102280 non-null  float64
 23  availability 365                102151 non-null  float64
 24  house_rules                     50468 non-null   object
 25  license                         2 non-null       object
dtypes: float64(9), int64(2), object(15)
memory usage: 20.4+ MB

## delete the unwanted columns

In [230]:
df.columns

Index(['id', 'NAME', 'host id', 'host_identity_verified', 'host name',
       'neighbourhood group', 'neighbourhood', 'lat', 'long', 'country',
       'country code', 'instant_bookable', 'cancellation_policy', 'room type',
       'Construction year', 'price', 'service fee', 'minimum nights',
       'number of reviews', 'last review', 'reviews per month',
       'review rate number', 'calculated host listings count',
       'availability 365', 'house_rules', 'license'],
      dtype='object')

In [231]:
column_to_drop = ['reviews per month',
       'review rate number', 'calculated host listings count',
       'availability 365', 'house_rules', 'license', 'id' ]

In [232]:
len(column_to_drop)

7

In [233]:
df = df.drop(columns = column_to_drop)

In [234]:
df

,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,country code,instant_bookable,cancellation_policy,room type,Construction year,price,service fee,minimum nights,number of reviews,last review
0,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,False,strict,Private room,2020.0,$966,$193,10.0,9.0,10/19/2021
1,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,False,moderate,Entire home/apt,2007.0,$142,$28,30.0,45.0,5/21/2022
2,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,US,True,flexible,Private room,2005.0,$620,$124,3.0,0.0,NaN
3,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,US,True,moderate,Entire home/apt,2005.0,$368,$74,30.0,270.0,7/5/2019
4,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,False,moderate,Entire home/apt,2009.0,$204,$41,10.0,9.0,11/19/2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102594,Spare room in Williamsburg,12312296767,verified,Krik,Brooklyn,Williamsburg,40.70862,-73.94651,United States,US,False,flexible,Private room,2003.0,$844,$169,1.0,0.0,NaN
102595,Best Location near Columbia U,77864383453,unconfirmed,Mifan,Manhattan,Morningside Heights,40.80460,-73.96545,United States,US,True,moderate,Private room,2016.0,$837,$167,1.0,1.0,7/6/2015
102596,"Comfy, bright room in Brooklyn",69050334417,unconfirmed,Megan,Brooklyn,Park Slope,40.67505,-73.98045,United States,US,True,moderate,Private room,2009.0,$988,$198,3.0,0.0,NaN
102597,Big Studio-One Stop from Midtown,11160591270,unconfirmed,Christopher,Queens,Long Island City,40.74989,-73.93777,United States,US,True,strict,Entire home/apt,2015.0,$546,$109,2.0,5.0,10/11/2015
102598,585 sf Luxury Studio,68170633372,unconfirmed,Rebecca,Manhattan,Upper West Side,40.76807,-73.98342,United States,US,False,flexible,Entire home/apt,2010.0,"$1,032",$206,1.0,0.0,NaN

In [235]:
df.shape

(102599, 19)

## Rename Columns

In [237]:
df.rename ( columns ={ "NAME" : "Name"}, inplace = True)

In [238]:
df

,Name,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,country code,instant_bookable,cancellation_policy,room type,Construction year,price,service fee,minimum nights,number of reviews,last review
0,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,False,strict,Private room,2020.0,$966,$193,10.0,9.0,10/19/2021
1,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,False,moderate,Entire home/apt,2007.0,$142,$28,30.0,45.0,5/21/2022
2,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,US,True,flexible,Private room,2005.0,$620,$124,3.0,0.0,NaN
3,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,US,True,moderate,Entire home/apt,2005.0,$368,$74,30.0,270.0,7/5/2019
4,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,False,moderate,Entire home/apt,2009.0,$204,$41,10.0,9.0,11/19/2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102594,Spare room in Williamsburg,12312296767,verified,Krik,Brooklyn,Williamsburg,40.70862,-73.94651,United States,US,False,flexible,Private room,2003.0,$844,$169,1.0,0.0,NaN
102595,Best Location near Columbia U,77864383453,unconfirmed,Mifan,Manhattan,Morningside Heights,40.80460,-73.96545,United States,US,True,moderate,Private room,2016.0,$837,$167,1.0,1.0,7/6/2015
102596,"Comfy, bright room in Brooklyn",69050334417,unconfirmed,Megan,Brooklyn,Park Slope,40.67505,-73.98045,United States,US,True,moderate,Private room,2009.0,$988,$198,3.0,0.0,NaN
102597,Big Studio-One Stop from Midtown,11160591270,unconfirmed,Christopher,Queens,Long Island City,40.74989,-73.93777,United States,US,True,strict,Entire home/apt,2015.0,$546,$109,2.0,5.0,10/11/2015
102598,585 sf Luxury Studio,68170633372,unconfirmed,Rebecca,Manhattan,Upper West Side,40.76807,-73.98342,United States,US,False,flexible,Entire home/apt,2010.0,"$1,032",$206,1.0,0.0,NaN

In [239]:
df.columns

Index(['Name', 'host id', 'host_identity_verified', 'host name',
       'neighbourhood group', 'neighbourhood', 'lat', 'long', 'country',
       'country code', 'instant_bookable', 'cancellation_policy', 'room type',
       'Construction year', 'price', 'service fee', 'minimum nights',
       'number of reviews', 'last review'],
      dtype='object')

In [240]:
new_column_name = []
for i in df.columns:
    new_column_name.append(i.capitalize())

In [241]:
new_column_name

['Name',
 'Host id',
 'Host_identity_verified',
 'Host name',
 'Neighbourhood group',
 'Neighbourhood',
 'Lat',
 'Long',
 'Country',
 'Country code',
 'Instant_bookable',
 'Cancellation_policy',
 'Room type',
 'Construction year',
 'Price',
 'Service fee',
 'Minimum nights',
 'Number of reviews',
 'Last review']

In [242]:
df.columns = new_column_name

In [243]:
df.columns

Index(['Name', 'Host id', 'Host_identity_verified', 'Host name',
       'Neighbourhood group', 'Neighbourhood', 'Lat', 'Long', 'Country',
       'Country code', 'Instant_bookable', 'Cancellation_policy', 'Room type',
       'Construction year', 'Price', 'Service fee', 'Minimum nights',
       'Number of reviews', 'Last review'],
      dtype='object')

In [244]:
df

,Name,Host id,Host_identity_verified,Host name,Neighbourhood group,Neighbourhood,Lat,Long,Country,Country code,Instant_bookable,Cancellation_policy,Room type,Construction year,Price,Service fee,Minimum nights,Number of reviews,Last review
0,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,False,strict,Private room,2020.0,$966,$193,10.0,9.0,10/19/2021
1,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,False,moderate,Entire home/apt,2007.0,$142,$28,30.0,45.0,5/21/2022
2,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,US,True,flexible,Private room,2005.0,$620,$124,3.0,0.0,NaN
3,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,US,True,moderate,Entire home/apt,2005.0,$368,$74,30.0,270.0,7/5/2019
4,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,False,moderate,Entire home/apt,2009.0,$204,$41,10.0,9.0,11/19/2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102594,Spare room in Williamsburg,12312296767,verified,Krik,Brooklyn,Williamsburg,40.70862,-73.94651,United States,US,False,flexible,Private room,2003.0,$844,$169,1.0,0.0,NaN
102595,Best Location near Columbia U,77864383453,unconfirmed,Mifan,Manhattan,Morningside Heights,40.80460,-73.96545,United States,US,True,moderate,Private room,2016.0,$837,$167,1.0,1.0,7/6/2015
102596,"Comfy, bright room in Brooklyn",69050334417,unconfirmed,Megan,Brooklyn,Park Slope,40.67505,-73.98045,United States,US,True,moderate,Private room,2009.0,$988,$198,3.0,0.0,NaN
102597,Big Studio-One Stop from Midtown,11160591270,unconfirmed,Christopher,Queens,Long Island City,40.74989,-73.93777,United States,US,True,strict,Entire home/apt,2015.0,$546,$109,2.0,5.0,10/11/2015
102598,585 sf Luxury Studio,68170633372,unconfirmed,Rebecca,Manhattan,Upper West Side,40.76807,-73.98342,United States,US,False,flexible,Entire home/apt,2010.0,"$1,032",$206,1.0,0.0,NaN

## Droping duplicates

In [246]:
df.duplicated()

0         False
1         False
2         False
3         False
4         False
          ...
102594     True
102595     True
102596     True
102597     True
102598     True
Length: 102599, dtype: bool

In [247]:
df.duplicated().sum()

np.int64(541)

In [248]:
df.duplicated().value_counts()

False    102058
True        541
Name: count, dtype: int64

In [249]:
df = df.drop_duplicates()

In [250]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 102058 entries, 0 to 102057
Data columns (total 19 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   Name                    101808 non-null  object
 1   Host id                 102058 non-null  int64
 2   Host_identity_verified  101769 non-null  object
 3   Host name               101654 non-null  object
 4   Neighbourhood group     102029 non-null  object
 5   Neighbourhood           102042 non-null  object
 6   Lat                     102050 non-null  float64
 7   Long                    102050 non-null  float64
 8   Country                 101526 non-null  object
 9   Country code            101927 non-null  object
 10  Instant_bookable        101953 non-null  object
 11  Cancellation_policy     101982 non-null  object
 12  Room type               102058 non-null  object
 13  Construction year       101844 non-null  float64
 14  Price                   101811 non-null  object
 15  Service fee             101785 non-null  object
 16  Minimum nights          101658 non-null  float64
 17  Number of reviews       101875 non-null  float64
 18  Last review             86226 non-null   object
dtypes: float64(5), int64(1), object(13)
memory usage: 15.6+ MB

## Remove NaN values

In [252]:
df.isna().sum()

Name                        250
Host id                       0
Host_identity_verified      289
Host name                   404
Neighbourhood group          29
Neighbourhood                16
Lat                           8
Long                          8
Country                     532
Country code                131
Instant_bookable            105
Cancellation_policy          76
Room type                     0
Construction year           214
Price                       247
Service fee                 273
Minimum nights              400
Number of reviews           183
Last review               15832
dtype: int64

In [253]:
# drop last review column
df = df.drop(columns=['Last review'])

In [254]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 102058 entries, 0 to 102057
Data columns (total 18 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   Name                    101808 non-null  object
 1   Host id                 102058 non-null  int64
 2   Host_identity_verified  101769 non-null  object
 3   Host name               101654 non-null  object
 4   Neighbourhood group     102029 non-null  object
 5   Neighbourhood           102042 non-null  object
 6   Lat                     102050 non-null  float64
 7   Long                    102050 non-null  float64
 8   Country                 101526 non-null  object
 9   Country code            101927 non-null  object
 10  Instant_bookable        101953 non-null  object
 11  Cancellation_policy     101982 non-null  object
 12  Room type               102058 non-null  object
 13  Construction year       101844 non-null  float64
 14  Price                   101811 non-null  object
 15  Service fee             101785 non-null  object
 16  Minimum nights          101658 non-null  float64
 17  Number of reviews       101875 non-null  float64
dtypes: float64(5), int64(1), object(12)
memory usage: 14.8+ MB

In [255]:
# drop Nan
df = df.dropna()

In [256]:
df.isna().sum()

Name                      0
Host id                   0
Host_identity_verified    0
Host name                 0
Neighbourhood group       0
Neighbourhood             0
Lat                       0
Long                      0
Country                   0
Country code              0
Instant_bookable          0
Cancellation_policy       0
Room type                 0
Construction year         0
Price                     0
Service fee               0
Minimum nights            0
Number of reviews         0
dtype: int64

In [257]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 99342 entries, 0 to 102040
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Name                    99342 non-null  object
 1   Host id                 99342 non-null  int64
 2   Host_identity_verified  99342 non-null  object
 3   Host name               99342 non-null  object
 4   Neighbourhood group     99342 non-null  object
 5   Neighbourhood           99342 non-null  object
 6   Lat                     99342 non-null  float64
 7   Long                    99342 non-null  float64
 8   Country                 99342 non-null  object
 9   Country code            99342 non-null  object
 10  Instant_bookable        99342 non-null  object
 11  Cancellation_policy     99342 non-null  object
 12  Room type               99342 non-null  object
 13  Construction year       99342 non-null  float64
 14  Price                   99342 non-null  object
 15  Service fee             99342 non-null  object
 16  Minimum nights          99342 non-null  float64
 17  Number of reviews       99342 non-null  float64
dtypes: float64(5), int64(1), object(12)
memory usage: 14.4+ MB

## Cleaning colum indutially

In [259]:
df

,Name,Host id,Host_identity_verified,Host name,Neighbourhood group,Neighbourhood,Lat,Long,Country,Country code,Instant_bookable,Cancellation_policy,Room type,Construction year,Price,Service fee,Minimum nights,Number of reviews
0,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,False,strict,Private room,2020.0,$966,$193,10.0,9.0
1,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,False,moderate,Entire home/apt,2007.0,$142,$28,30.0,45.0
4,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,False,moderate,Entire home/apt,2009.0,$204,$41,10.0,9.0
5,Large Cozy 1 BR Apartment In Midtown East,45498551794,verified,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,United States,US,True,flexible,Entire home/apt,2013.0,$577,$115,3.0,74.0
7,BlissArtsSpace!,90821839709,unconfirmed,Emma,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,United States,US,False,moderate,Private room,2009.0,"$1,060",$212,45.0,49.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102029,Cozy room in a 2B with backyard access,5155155913,unconfirmed,Cristina,Queens,Astoria,40.76987,-73.92679,United States,US,False,flexible,Private room,2018.0,$822,$164,1.0,9.0
102030,An East Williamsburg Delight,71564706996,verified,Petra,Brooklyn,Bedford-Stuyvesant,40.68335,-73.91222,United States,US,True,moderate,Private room,2015.0,$455,$91,4.0,36.0
102031,Cozy bedroom in williamsburg,83101851929,verified,Russell,Brooklyn,Williamsburg,40.70870,-73.96710,United States,US,True,flexible,Private room,2020.0,"$1,078",$216,1.0,58.0
102032,Spacious Room w/ 2 Bed,69037598918,unconfirmed,Christine,Queens,Bayside,40.75047,-73.75349,United States,US,False,moderate,Private room,2007.0,$103,$21,7.0,40.0
102040,"Room in Queens, NY, near LGA.",56457739998,verified,Sonia,Queens,East Elmhurst,40.76245,-73.87938,United States,US,True,strict,Private room,2022.0,$982,$196,1.0,239.0

chage case in Host_identity_verified

In [261]:
df["Host_identity_verified"] = df["Host_identity_verified"].str.upper()

In [262]:
df

,Name,Host id,Host_identity_verified,Host name,Neighbourhood group,Neighbourhood,Lat,Long,Country,Country code,Instant_bookable,Cancellation_policy,Room type,Construction year,Price,Service fee,Minimum nights,Number of reviews
0,Clean & quiet apt home by the park,80014485718,UNCONFIRMED,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,False,strict,Private room,2020.0,$966,$193,10.0,9.0
1,Skylit Midtown Castle,52335172823,VERIFIED,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,False,moderate,Entire home/apt,2007.0,$142,$28,30.0,45.0
4,Entire Apt: Spacious Studio/Loft by central park,92037596077,VERIFIED,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,False,moderate,Entire home/apt,2009.0,$204,$41,10.0,9.0
5,Large Cozy 1 BR Apartment In Midtown East,45498551794,VERIFIED,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,United States,US,True,flexible,Entire home/apt,2013.0,$577,$115,3.0,74.0
7,BlissArtsSpace!,90821839709,UNCONFIRMED,Emma,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,United States,US,False,moderate,Private room,2009.0,"$1,060",$212,45.0,49.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102029,Cozy room in a 2B with backyard access,5155155913,UNCONFIRMED,Cristina,Queens,Astoria,40.76987,-73.92679,United States,US,False,flexible,Private room,2018.0,$822,$164,1.0,9.0
102030,An East Williamsburg Delight,71564706996,VERIFIED,Petra,Brooklyn,Bedford-Stuyvesant,40.68335,-73.91222,United States,US,True,moderate,Private room,2015.0,$455,$91,4.0,36.0
102031,Cozy bedroom in williamsburg,83101851929,VERIFIED,Russell,Brooklyn,Williamsburg,40.70870,-73.96710,United States,US,True,flexible,Private room,2020.0,"$1,078",$216,1.0,58.0
102032,Spacious Room w/ 2 Bed,69037598918,UNCONFIRMED,Christine,Queens,Bayside,40.75047,-73.75349,United States,US,False,moderate,Private room,2007.0,$103,$21,7.0,40.0
102040,"Room in Queens, NY, near LGA.",56457739998,VERIFIED,Sonia,Queens,East Elmhurst,40.76245,-73.87938,United States,US,True,strict,Private room,2022.0,$982,$196,1.0,239.0

In [263]:
# Chage Instant_bookable column boolean to numeric

In [264]:
df["Instant_bookable"].apply( lambda x:1 if x == True else 0 )

0         0
1         0
4         0
5         1
7         0
         ..
102029    0
102030    1
102031    1
102032    0
102040    1
Name: Instant_bookable, Length: 99342, dtype: int64

In [265]:
df["Instant_bookable"] = df["Instant_bookable"].apply( lambda x:1 if x == True else 0 )

In [266]:
df["Instant_bookable"].dtype

dtype('int64')

## Change index series

In [268]:
df.index

Index([     0,      1,      4,      5,      7,      8,      9,     10,     11,
           13,
       ...
       102024, 102025, 102026, 102027, 102028, 102029, 102030, 102031, 102032,
       102040],
      dtype='int64', length=99342)

In [269]:
# Reset index
df = df.reset_index()

In [270]:
df

,index,Name,Host id,Host_identity_verified,Host name,Neighbourhood group,Neighbourhood,Lat,Long,Country,Country code,Instant_bookable,Cancellation_policy,Room type,Construction year,Price,Service fee,Minimum nights,Number of reviews
0,0,Clean & quiet apt home by the park,80014485718,UNCONFIRMED,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,0,strict,Private room,2020.0,$966,$193,10.0,9.0
1,1,Skylit Midtown Castle,52335172823,VERIFIED,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,0,moderate,Entire home/apt,2007.0,$142,$28,30.0,45.0
2,4,Entire Apt: Spacious Studio/Loft by central park,92037596077,VERIFIED,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,0,moderate,Entire home/apt,2009.0,$204,$41,10.0,9.0
3,5,Large Cozy 1 BR Apartment In Midtown East,45498551794,VERIFIED,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,United States,US,1,flexible,Entire home/apt,2013.0,$577,$115,3.0,74.0
4,7,BlissArtsSpace!,90821839709,UNCONFIRMED,Emma,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,United States,US,0,moderate,Private room,2009.0,"$1,060",$212,45.0,49.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99337,102029,Cozy room in a 2B with backyard access,5155155913,UNCONFIRMED,Cristina,Queens,Astoria,40.76987,-73.92679,United States,US,0,flexible,Private room,2018.0,$822,$164,1.0,9.0
99338,102030,An East Williamsburg Delight,71564706996,VERIFIED,Petra,Brooklyn,Bedford-Stuyvesant,40.68335,-73.91222,United States,US,1,moderate,Private room,2015.0,$455,$91,4.0,36.0
99339,102031,Cozy bedroom in williamsburg,83101851929,VERIFIED,Russell,Brooklyn,Williamsburg,40.70870,-73.96710,United States,US,1,flexible,Private room,2020.0,"$1,078",$216,1.0,58.0
99340,102032,Spacious Room w/ 2 Bed,69037598918,UNCONFIRMED,Christine,Queens,Bayside,40.75047,-73.75349,United States,US,0,moderate,Private room,2007.0,$103,$21,7.0,40.0
99341,102040,"Room in Queens, NY, near LGA.",56457739998,VERIFIED,Sonia,Queens,East Elmhurst,40.76245,-73.87938,United States,US,1,strict,Private room,2022.0,$982,$196,1.0,239.0

In [271]:
# drop old index column
df = df.drop(columns = "index")

In [272]:
df

,Name,Host id,Host_identity_verified,Host name,Neighbourhood group,Neighbourhood,Lat,Long,Country,Country code,Instant_bookable,Cancellation_policy,Room type,Construction year,Price,Service fee,Minimum nights,Number of reviews
0,Clean & quiet apt home by the park,80014485718,UNCONFIRMED,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,0,strict,Private room,2020.0,$966,$193,10.0,9.0
1,Skylit Midtown Castle,52335172823,VERIFIED,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,0,moderate,Entire home/apt,2007.0,$142,$28,30.0,45.0
2,Entire Apt: Spacious Studio/Loft by central park,92037596077,VERIFIED,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,0,moderate,Entire home/apt,2009.0,$204,$41,10.0,9.0
3,Large Cozy 1 BR Apartment In Midtown East,45498551794,VERIFIED,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,United States,US,1,flexible,Entire home/apt,2013.0,$577,$115,3.0,74.0
4,BlissArtsSpace!,90821839709,UNCONFIRMED,Emma,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,United States,US,0,moderate,Private room,2009.0,"$1,060",$212,45.0,49.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99337,Cozy room in a 2B with backyard access,5155155913,UNCONFIRMED,Cristina,Queens,Astoria,40.76987,-73.92679,United States,US,0,flexible,Private room,2018.0,$822,$164,1.0,9.0
99338,An East Williamsburg Delight,71564706996,VERIFIED,Petra,Brooklyn,Bedford-Stuyvesant,40.68335,-73.91222,United States,US,1,moderate,Private room,2015.0,$455,$91,4.0,36.0
99339,Cozy bedroom in williamsburg,83101851929,VERIFIED,Russell,Brooklyn,Williamsburg,40.70870,-73.96710,United States,US,1,flexible,Private room,2020.0,"$1,078",$216,1.0,58.0
99340,Spacious Room w/ 2 Bed,69037598918,UNCONFIRMED,Christine,Queens,Bayside,40.75047,-73.75349,United States,US,0,moderate,Private room,2007.0,$103,$21,7.0,40.0
99341,"Room in Queens, NY, near LGA.",56457739998,VERIFIED,Sonia,Queens,East Elmhurst,40.76245,-73.87938,United States,US,1,strict,Private room,2022.0,$982,$196,1.0,239.0

# Column wise cleaning 
## Change Price & Serice fee column into float 
## to do that remove $ symbole

In [274]:
df["Price"] = df["Price"].str.replace("$","")

In [275]:
df["Price"] = df["Price"].str.replace(" ","")

In [276]:
df["Price"] = df["Price"].str.replace(",","")

In [329]:
df["Price"] = df["Price"].astype(int)

In [333]:
df["Service fee"] = df["Service fee"].str.replace("$","")

In [335]:
df["Service fee"].astype(int)

0        193
1         28
2         41
3        115
4        212
        ...
99337    164
99338     91
99339    216
99340     21
99341    196
Name: Service fee, Length: 99342, dtype: int64

In [337]:
df

,Name,Host id,Host_identity_verified,Host name,Neighbourhood group,Neighbourhood,Lat,Long,Country,Country code,Instant_bookable,Cancellation_policy,Room type,Construction year,Price,Service fee,Minimum nights,Number of reviews
0,Clean & quiet apt home by the park,80014485718,UNCONFIRMED,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,0,strict,Private room,2020.0,966,193,10.0,9.0
1,Skylit Midtown Castle,52335172823,VERIFIED,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,0,moderate,Entire home/apt,2007.0,142,28,30.0,45.0
2,Entire Apt: Spacious Studio/Loft by central park,92037596077,VERIFIED,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,0,moderate,Entire home/apt,2009.0,204,41,10.0,9.0
3,Large Cozy 1 BR Apartment In Midtown East,45498551794,VERIFIED,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,United States,US,1,flexible,Entire home/apt,2013.0,577,115,3.0,74.0
4,BlissArtsSpace!,90821839709,UNCONFIRMED,Emma,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,United States,US,0,moderate,Private room,2009.0,1060,212,45.0,49.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99337,Cozy room in a 2B with backyard access,5155155913,UNCONFIRMED,Cristina,Queens,Astoria,40.76987,-73.92679,United States,US,0,flexible,Private room,2018.0,822,164,1.0,9.0
99338,An East Williamsburg Delight,71564706996,VERIFIED,Petra,Brooklyn,Bedford-Stuyvesant,40.68335,-73.91222,United States,US,1,moderate,Private room,2015.0,455,91,4.0,36.0
99339,Cozy bedroom in williamsburg,83101851929,VERIFIED,Russell,Brooklyn,Williamsburg,40.70870,-73.96710,United States,US,1,flexible,Private room,2020.0,1078,216,1.0,58.0
99340,Spacious Room w/ 2 Bed,69037598918,UNCONFIRMED,Christine,Queens,Bayside,40.75047,-73.75349,United States,US,0,moderate,Private room,2007.0,103,21,7.0,40.0
99341,"Room in Queens, NY, near LGA.",56457739998,VERIFIED,Sonia,Queens,East Elmhurst,40.76245,-73.87938,United States,US,1,strict,Private room,2022.0,982,196,1.0,239.0

In [339]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99342 entries, 0 to 99341
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Name                    99342 non-null  object
 1   Host id                 99342 non-null  int64
 2   Host_identity_verified  99342 non-null  object
 3   Host name               99342 non-null  object
 4   Neighbourhood group     99342 non-null  object
 5   Neighbourhood           99342 non-null  object
 6   Lat                     99342 non-null  float64
 7   Long                    99342 non-null  float64
 8   Country                 99342 non-null  object
 9   Country code            99342 non-null  object
 10  Instant_bookable        99342 non-null  int64
 11  Cancellation_policy     99342 non-null  object
 12  Room type               99342 non-null  object
 13  Construction year       99342 non-null  float64
 14  Price                   99342 non-null  int64
 15  Service fee             99342 non-null  object
 16  Minimum nights          99342 non-null  float64
 17  Number of reviews       99342 non-null  float64
dtypes: float64(5), int64(3), object(10)
memory usage: 13.6+ MB

In [341]:
# Change type of Minimum nights column and number of review
df["Minimum nights"] = df["Minimum nights"].astype(int)

In [345]:
df["Number of reviews"] = df["Number of reviews"].astype(int)

In [347]:
df

,Name,Host id,Host_identity_verified,Host name,Neighbourhood group,Neighbourhood,Lat,Long,Country,Country code,Instant_bookable,Cancellation_policy,Room type,Construction year,Price,Service fee,Minimum nights,Number of reviews
0,Clean & quiet apt home by the park,80014485718,UNCONFIRMED,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,0,strict,Private room,2020.0,966,193,10,9
1,Skylit Midtown Castle,52335172823,VERIFIED,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,0,moderate,Entire home/apt,2007.0,142,28,30,45
2,Entire Apt: Spacious Studio/Loft by central park,92037596077,VERIFIED,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,0,moderate,Entire home/apt,2009.0,204,41,10,9
3,Large Cozy 1 BR Apartment In Midtown East,45498551794,VERIFIED,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,United States,US,1,flexible,Entire home/apt,2013.0,577,115,3,74
4,BlissArtsSpace!,90821839709,UNCONFIRMED,Emma,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,United States,US,0,moderate,Private room,2009.0,1060,212,45,49
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99337,Cozy room in a 2B with backyard access,5155155913,UNCONFIRMED,Cristina,Queens,Astoria,40.76987,-73.92679,United States,US,0,flexible,Private room,2018.0,822,164,1,9
99338,An East Williamsburg Delight,71564706996,VERIFIED,Petra,Brooklyn,Bedford-Stuyvesant,40.68335,-73.91222,United States,US,1,moderate,Private room,2015.0,455,91,4,36
99339,Cozy bedroom in williamsburg,83101851929,VERIFIED,Russell,Brooklyn,Williamsburg,40.70870,-73.96710,United States,US,1,flexible,Private room,2020.0,1078,216,1,58
99340,Spacious Room w/ 2 Bed,69037598918,UNCONFIRMED,Christine,Queens,Bayside,40.75047,-73.75349,United States,US,0,moderate,Private room,2007.0,103,21,7,40
99341,"Room in Queens, NY, near LGA.",56457739998,VERIFIED,Sonia,Queens,East Elmhurst,40.76245,-73.87938,United States,US,1,strict,Private room,2022.0,982,196,1,239

In [349]:
df["Country code"].unique()

array(['US'], dtype=object)

In [351]:
df["Country"].unique()

array(['United States'], dtype=object)

In [355]:
# As seen the unquie  value of the column no need 2 of them  drop one 

df = df.drop(columns = "Country")

In [357]:
df

,Name,Host id,Host_identity_verified,Host name,Neighbourhood group,Neighbourhood,Lat,Long,Country code,Instant_bookable,Cancellation_policy,Room type,Construction year,Price,Service fee,Minimum nights,Number of reviews
0,Clean & quiet apt home by the park,80014485718,UNCONFIRMED,Madaline,Brooklyn,Kensington,40.64749,-73.97237,US,0,strict,Private room,2020.0,966,193,10,9
1,Skylit Midtown Castle,52335172823,VERIFIED,Jenna,Manhattan,Midtown,40.75362,-73.98377,US,0,moderate,Entire home/apt,2007.0,142,28,30,45
2,Entire Apt: Spacious Studio/Loft by central park,92037596077,VERIFIED,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,US,0,moderate,Entire home/apt,2009.0,204,41,10,9
3,Large Cozy 1 BR Apartment In Midtown East,45498551794,VERIFIED,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,US,1,flexible,Entire home/apt,2013.0,577,115,3,74
4,BlissArtsSpace!,90821839709,UNCONFIRMED,Emma,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,US,0,moderate,Private room,2009.0,1060,212,45,49
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99337,Cozy room in a 2B with backyard access,5155155913,UNCONFIRMED,Cristina,Queens,Astoria,40.76987,-73.92679,US,0,flexible,Private room,2018.0,822,164,1,9
99338,An East Williamsburg Delight,71564706996,VERIFIED,Petra,Brooklyn,Bedford-Stuyvesant,40.68335,-73.91222,US,1,moderate,Private room,2015.0,455,91,4,36
99339,Cozy bedroom in williamsburg,83101851929,VERIFIED,Russell,Brooklyn,Williamsburg,40.70870,-73.96710,US,1,flexible,Private room,2020.0,1078,216,1,58
99340,Spacious Room w/ 2 Bed,69037598918,UNCONFIRMED,Christine,Queens,Bayside,40.75047,-73.75349,US,0,moderate,Private room,2007.0,103,21,7,40
99341,"Room in Queens, NY, near LGA.",56457739998,VERIFIED,Sonia,Queens,East Elmhurst,40.76245,-73.87938,US,1,strict,Private room,2022.0,982,196,1,239

In [368]:
# Chnge intial letter as caps in column Cancellation_policy
df["Cancellation_policy"] = df["Cancellation_policy"].str.capitalize()
df

,Name,Host id,Host_identity_verified,Host name,Neighbourhood group,Neighbourhood,Lat,Long,Country code,Instant_bookable,Cancellation_policy,Room type,Construction year,Price,Service fee,Minimum nights,Number of reviews
0,Clean & quiet apt home by the park,80014485718,UNCONFIRMED,Madaline,Brooklyn,Kensington,40.64749,-73.97237,US,0,Strict,Private room,2020.0,966,193,10,9
1,Skylit Midtown Castle,52335172823,VERIFIED,Jenna,Manhattan,Midtown,40.75362,-73.98377,US,0,Moderate,Entire home/apt,2007.0,142,28,30,45
2,Entire Apt: Spacious Studio/Loft by central park,92037596077,VERIFIED,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,US,0,Moderate,Entire home/apt,2009.0,204,41,10,9
3,Large Cozy 1 BR Apartment In Midtown East,45498551794,VERIFIED,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,US,1,Flexible,Entire home/apt,2013.0,577,115,3,74
4,BlissArtsSpace!,90821839709,UNCONFIRMED,Emma,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,US,0,Moderate,Private room,2009.0,1060,212,45,49
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99337,Cozy room in a 2B with backyard access,5155155913,UNCONFIRMED,Cristina,Queens,Astoria,40.76987,-73.92679,US,0,Flexible,Private room,2018.0,822,164,1,9
99338,An East Williamsburg Delight,71564706996,VERIFIED,Petra,Brooklyn,Bedford-Stuyvesant,40.68335,-73.91222,US,1,Moderate,Private room,2015.0,455,91,4,36
99339,Cozy bedroom in williamsburg,83101851929,VERIFIED,Russell,Brooklyn,Williamsburg,40.70870,-73.96710,US,1,Flexible,Private room,2020.0,1078,216,1,58
99340,Spacious Room w/ 2 Bed,69037598918,UNCONFIRMED,Christine,Queens,Bayside,40.75047,-73.75349,US,0,Moderate,Private room,2007.0,103,21,7,40
99341,"Room in Queens, NY, near LGA.",56457739998,VERIFIED,Sonia,Queens,East Elmhurst,40.76245,-73.87938,US,1,Strict,Private room,2022.0,982,196,1,239

In [370]:
# Change type of Construction year
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99342 entries, 0 to 99341
Data columns (total 17 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Name                    99342 non-null  object
 1   Host id                 99342 non-null  int64
 2   Host_identity_verified  99342 non-null  object
 3   Host name               99342 non-null  object
 4   Neighbourhood group     99342 non-null  object
 5   Neighbourhood           99342 non-null  object
 6   Lat                     99342 non-null  float64
 7   Long                    99342 non-null  float64
 8   Country code            99342 non-null  object
 9   Instant_bookable        99342 non-null  int64
 10  Cancellation_policy     99342 non-null  object
 11  Room type               99342 non-null  object
 12  Construction year       99342 non-null  float64
 13  Price                   99342 non-null  int64
 14  Service fee             99342 non-null  object
 15  Minimum nights          99342 non-null  int64
 16  Number of reviews       99342 non-null  int64
dtypes: float64(3), int64(5), object(9)
memory usage: 12.9+ MB

In [374]:
df["Construction year"] = df["Construction year"].astype(int)

In [378]:
df

,Name,Host id,Host_identity_verified,Host name,Neighbourhood group,Neighbourhood,Lat,Long,Country code,Instant_bookable,Cancellation_policy,Room type,Construction year,Price,Service fee,Minimum nights,Number of reviews
0,Clean & quiet apt home by the park,80014485718,UNCONFIRMED,Madaline,Brooklyn,Kensington,40.64749,-73.97237,US,0,Strict,Private room,2020,966,193,10,9
1,Skylit Midtown Castle,52335172823,VERIFIED,Jenna,Manhattan,Midtown,40.75362,-73.98377,US,0,Moderate,Entire home/apt,2007,142,28,30,45
2,Entire Apt: Spacious Studio/Loft by central park,92037596077,VERIFIED,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,US,0,Moderate,Entire home/apt,2009,204,41,10,9
3,Large Cozy 1 BR Apartment In Midtown East,45498551794,VERIFIED,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,US,1,Flexible,Entire home/apt,2013,577,115,3,74
4,BlissArtsSpace!,90821839709,UNCONFIRMED,Emma,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,US,0,Moderate,Private room,2009,1060,212,45,49
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99337,Cozy room in a 2B with backyard access,5155155913,UNCONFIRMED,Cristina,Queens,Astoria,40.76987,-73.92679,US,0,Flexible,Private room,2018,822,164,1,9
99338,An East Williamsburg Delight,71564706996,VERIFIED,Petra,Brooklyn,Bedford-Stuyvesant,40.68335,-73.91222,US,1,Moderate,Private room,2015,455,91,4,36
99339,Cozy bedroom in williamsburg,83101851929,VERIFIED,Russell,Brooklyn,Williamsburg,40.70870,-73.96710,US,1,Flexible,Private room,2020,1078,216,1,58
99340,Spacious Room w/ 2 Bed,69037598918,UNCONFIRMED,Christine,Queens,Bayside,40.75047,-73.75349,US,0,Moderate,Private room,2007,103,21,7,40
99341,"Room in Queens, NY, near LGA.",56457739998,VERIFIED,Sonia,Queens,East Elmhurst,40.76245,-73.87938,US,1,Strict,Private room,2022,982,196,1,239

In [380]:
# combining Lat Long Column

df["Lat"] + df["Long"]

0       -33.32488
1       -33.23015
2       -33.14548
3       -33.22733
4       -33.26908
           ...
99337   -33.15692
99338   -33.22887
99339   -33.25840
99340   -33.00302
99341   -33.11693
Length: 99342, dtype: float64

In [384]:
# its in float need to change in to string 
df["Lat"] = df["Lat"].astype(str)

In [386]:
df["Long"] = df["Long"].astype(str)

In [400]:
df["Lat"] = (df["Lat"] + df["Long"])

In [408]:
# Drop Long column
df = df.drop(columns = "Long")

In [416]:
# Rename Lat column into Long 

df = df.rename(columns = {"Lat" : "Lat_Long"})

In [422]:
df

,Name,Host id,Host_identity_verified,Host name,Neighbourhood group,Neighbourhood,Lat_Long,Country code,Instant_bookable,Cancellation_policy,Room type,Construction year,Price,Service fee,Minimum nights,Number of reviews
0,Clean & quiet apt home by the park,80014485718,UNCONFIRMED,Madaline,Brooklyn,Kensington,40.64749-73.97237,US,0,Strict,Private room,2020,966,193,10,9
1,Skylit Midtown Castle,52335172823,VERIFIED,Jenna,Manhattan,Midtown,40.75362-73.98377,US,0,Moderate,Entire home/apt,2007,142,28,30,45
2,Entire Apt: Spacious Studio/Loft by central park,92037596077,VERIFIED,Lyndon,Manhattan,East Harlem,40.79851-73.94399,US,0,Moderate,Entire home/apt,2009,204,41,10,9
3,Large Cozy 1 BR Apartment In Midtown East,45498551794,VERIFIED,Michelle,Manhattan,Murray Hill,40.74767-73.975,US,1,Flexible,Entire home/apt,2013,577,115,3,74
4,BlissArtsSpace!,90821839709,UNCONFIRMED,Emma,Brooklyn,Bedford-Stuyvesant,40.68688-73.95596,US,0,Moderate,Private room,2009,1060,212,45,49
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99337,Cozy room in a 2B with backyard access,5155155913,UNCONFIRMED,Cristina,Queens,Astoria,40.76987-73.92679,US,0,Flexible,Private room,2018,822,164,1,9
99338,An East Williamsburg Delight,71564706996,VERIFIED,Petra,Brooklyn,Bedford-Stuyvesant,40.68335-73.91222,US,1,Moderate,Private room,2015,455,91,4,36
99339,Cozy bedroom in williamsburg,83101851929,VERIFIED,Russell,Brooklyn,Williamsburg,40.7087-73.9671,US,1,Flexible,Private room,2020,1078,216,1,58
99340,Spacious Room w/ 2 Bed,69037598918,UNCONFIRMED,Christine,Queens,Bayside,40.75047-73.75349,US,0,Moderate,Private room,2007,103,21,7,40
99341,"Room in Queens, NY, near LGA.",56457739998,VERIFIED,Sonia,Queens,East Elmhurst,40.76245-73.87938,US,1,Strict,Private room,2022,982,196,1,239

In [434]:
df["Room type"].value_counts()

Room type
Entire home/apt    52054
Private room       45022
Shared room         2158
Hotel room           108
Name: count, dtype: int64

In [436]:
df.to_csv(r"D:\Data sets\Data cleaning Project\Pb5_Airbnb\Cleaned_Airbnb_Open_Data.csv")